/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AdminDashboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboardFrame
     */
    private String userId;
    private String username;
    
    public AdminDashboardFrame() {
        initComponents();
    }
     public AdminDashboardFrame(String userId, String username) {
        this.userId = userId;
        this.username = username;
        initComponents();
        setTitle("Admin Dashboard");
        this.setLocationRelativeTo(null); // Center the window
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Styles.GradientPanel();
        usernameTextField = new javax.swing.JLabel();
        btnLogOut = Styles.createRoundedButton("Logout");
        btnManageUsers = Styles.createRoundedButton("Manage User");
        btnViewAppoinment = Styles.createRoundedButton("View Appointment");
        btnManageCar = Styles.createRoundedButton("Manage Cars");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernameTextField.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        usernameTextField.setText("Welcome, Admin");

        btnLogOut.setBackground(new java.awt.Color(204, 51, 0));
        btnLogOut.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnManageUsers.setBackground(new java.awt.Color(0, 0, 0));
        btnManageUsers.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnManageUsers.setForeground(new java.awt.Color(255, 255, 255));
        btnManageUsers.setText("Manage User");
        btnManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUsersActionPerformed(evt);
            }
        });

        btnViewAppoinment.setBackground(new java.awt.Color(0, 0, 0));
        btnViewAppoinment.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnViewAppoinment.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAppoinment.setText("View Appointment");
        btnViewAppoinment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAppoinmentActionPerformed(evt);
            }
        });

        btnManageCar.setBackground(new java.awt.Color(0, 0, 0));
        btnManageCar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnManageCar.setForeground(new java.awt.Color(255, 255, 255));
        btnManageCar.setText("Manage Car");
        btnManageCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnManageUsers)
                .addGap(18, 18, 18)
                .addComponent(btnViewAppoinment)
                .addGap(18, 18, 18)
                .addComponent(btnManageCar)
                .addGap(0, 71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(usernameTextField)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnLogOut)
                .addGap(68, 68, 68)
                .addComponent(usernameTextField)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageUsers)
                    .addComponent(btnViewAppoinment)
                    .addComponent(btnManageCar))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUsersActionPerformed
        // TODO add your handling code here:
          // Open Manage Users Form and pass userId, username
        manageUsersFrame manageUsersFrame = new manageUsersFrame(userId, username);
        manageUsersFrame.setVisible(true);
        this.dispose(); // Close the Admin Dashboard frame // Close the Admin Dashboard frame
    }//GEN-LAST:event_btnManageUsersActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
          // Log out functionality
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Log Out", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose(); // Close the Admin Dashboard frame
            // Optionally, you could show a login screen again
            new LoginForm().setVisible(true);
        } // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnManageCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCarActionPerformed
// Open Manage Cars Form and pass userId, username
        manageCarsFrame manageCarsFrame = new manageCarsFrame(userId, username);
        manageCarsFrame.setVisible(true);
        this.dispose(); // Close the Admin Dashboard frame        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageCarActionPerformed

    private void btnViewAppoinmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAppoinmentActionPerformed
        ViewAppointmentsFrame viewAppointmentsFrame = new ViewAppointmentsFrame(userId, username);
        viewAppointmentsFrame.setVisible(true);
        this.dispose(); // Close the Admin Dashboard frame // Close the Admin Dashboard frame
    }//GEN-LAST:event_btnViewAppoinmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManageCar;
    private javax.swing.JButton btnManageUsers;
    private javax.swing.JButton btnViewAppoinment;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel usernameTextField;
    // End of variables declaration//GEN-END:variables
}
