/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.awt.Image;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Afifah
 */
public class AllModelFrame extends javax.swing.JFrame {

    private String userId;
    private String username;
    
    public AllModelFrame() {
        initComponents();
        setLocationRelativeTo(null); // Center the frame
        loadCarImages(); // Load images dynamically
    }

    public AllModelFrame(String userId, String username) {
        this.userId = userId;
        this.username = username;
        initComponents();
        setLocationRelativeTo(null); // Center the frame
        loadCarImages(); // Load images dynamically
    }

    // Fetch car images from the database
    //model
    private void loadCarImages() {
        String query = "SELECT model, image_path FROM car_details ORDER BY id ASC";

        try (Connection conn = DBConnection.getConnection(); // Reuse connection
             PreparedStatement stmt = conn.prepareStatement(query);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                String model = rs.getString("model");
                String imagePath = rs.getString("image_path");
                setLabelImage(model, imagePath);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        }
    }

    // Assigns image based on the car model.
    //view
    private void setLabelImage(String model, String imagePath) {
        JLabel targetLabel = null;

        switch (model) {
            case "S70":
                targetLabel = imgS70;
                break;
            case "X50":
                targetLabel = imgX50;
                break;
            case "X70":
                targetLabel = imgX70;
                break;
            case "Persona":
                targetLabel = imgPERSONA;
                break;
            case "Iriz":
                targetLabel = imgIRIZ;
                break;
            case "Saga":
                targetLabel = imgSAGA;
                break;
            default:
                System.out.println("No label found for model: " + model);
                return;
        }

        if (targetLabel != null) {
            try {
                ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource(imagePath));
                Image scaledImage = icon.getImage().getScaledInstance(targetLabel.getWidth(), targetLabel.getHeight(), Image.SCALE_SMOOTH);
                targetLabel.setIcon(new ImageIcon(scaledImage));

                targetLabel.revalidate();
                targetLabel.repaint();
                System.out.println("SUCCESS: Image loaded for " + model);
            } catch (Exception e) {
                System.out.println("ERROR: Unable to load image -> " + imagePath);
                targetLabel.setText("Image Not Found");
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new Styles.GradientPanel();
        lblTitle = new javax.swing.JLabel();
        backButton = Styles.createRoundedButton("Back");
        exitButton = Styles.createRoundedButton("Exit");
        S70 = new Styles.RoundedGradientPanel();
        lblS70 = new javax.swing.JLabel();
        imgS70 = new javax.swing.JLabel();
        X50 = new Styles.RoundedGradientPanel();
        lblX50 = new javax.swing.JLabel();
        imgX50 = new javax.swing.JLabel();
        X70 = new Styles.RoundedGradientPanel();
        lblX70 = new javax.swing.JLabel();
        imgX70 = new javax.swing.JLabel();
        PERSONA = new Styles.RoundedGradientPanel();
        lblPersona = new javax.swing.JLabel();
        imgPERSONA = new javax.swing.JLabel();
        IRIZ = new Styles.RoundedGradientPanel();
        lblIriz = new javax.swing.JLabel();
        imgIRIZ = new javax.swing.JLabel();
        SAGA = new Styles.RoundedGradientPanel();
        lblSaga = new javax.swing.JLabel();
        imgSAGA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Calculation System");

        lblTitle.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblTitle.setText("MODELS");

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(204, 51, 0));
        exitButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        S70.setBackground(new java.awt.Color(255, 255, 255));

        lblS70.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        lblS70.setText("PROTON S70");

        imgS70.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgS70MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout S70Layout = new javax.swing.GroupLayout(S70);
        S70.setLayout(S70Layout);
        S70Layout.setHorizontalGroup(
            S70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, S70Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblS70, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addComponent(imgS70, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        S70Layout.setVerticalGroup(
            S70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, S70Layout.createSequentialGroup()
                .addComponent(imgS70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblS70)
                .addContainerGap())
        );

        X50.setBackground(new java.awt.Color(255, 255, 255));

        lblX50.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        lblX50.setText("PROTON X50");

        imgX50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgX50MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout X50Layout = new javax.swing.GroupLayout(X50);
        X50.setLayout(X50Layout);
        X50Layout.setHorizontalGroup(
            X50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, X50Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(lblX50, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addComponent(imgX50, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        X50Layout.setVerticalGroup(
            X50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, X50Layout.createSequentialGroup()
                .addComponent(imgX50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblX50)
                .addContainerGap())
        );

        X70.setBackground(new java.awt.Color(255, 255, 255));

        lblX70.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        lblX70.setText("PROTON X70");

        imgX70.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgX70MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout X70Layout = new javax.swing.GroupLayout(X70);
        X70.setLayout(X70Layout);
        X70Layout.setHorizontalGroup(
            X70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, X70Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblX70, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addComponent(imgX70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        X70Layout.setVerticalGroup(
            X70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, X70Layout.createSequentialGroup()
                .addComponent(imgX70, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblX70)
                .addContainerGap())
        );

        PERSONA.setBackground(new java.awt.Color(255, 255, 255));

        lblPersona.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        lblPersona.setText("PROTON PERSONA");

        imgPERSONA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgPERSONAMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PERSONALayout = new javax.swing.GroupLayout(PERSONA);
        PERSONA.setLayout(PERSONALayout);
        PERSONALayout.setHorizontalGroup(
            PERSONALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PERSONALayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblPersona)
                .addContainerGap(69, Short.MAX_VALUE))
            .addComponent(imgPERSONA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PERSONALayout.setVerticalGroup(
            PERSONALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PERSONALayout.createSequentialGroup()
                .addComponent(imgPERSONA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPersona)
                .addContainerGap())
        );

        IRIZ.setBackground(new java.awt.Color(255, 255, 255));

        lblIriz.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        lblIriz.setText("PROTON IRIZ");

        imgIRIZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgIRIZMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout IRIZLayout = new javax.swing.GroupLayout(IRIZ);
        IRIZ.setLayout(IRIZLayout);
        IRIZLayout.setHorizontalGroup(
            IRIZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IRIZLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIriz)
                .addGap(89, 89, 89))
            .addComponent(imgIRIZ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        IRIZLayout.setVerticalGroup(
            IRIZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IRIZLayout.createSequentialGroup()
                .addComponent(imgIRIZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIriz)
                .addContainerGap())
        );

        SAGA.setBackground(new java.awt.Color(255, 255, 255));

        lblSaga.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        lblSaga.setText("PROTON SAGA");

        imgSAGA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgSAGAMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SAGALayout = new javax.swing.GroupLayout(SAGA);
        SAGA.setLayout(SAGALayout);
        SAGALayout.setHorizontalGroup(
            SAGALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SAGALayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(lblSaga)
                .addGap(79, 79, 79))
            .addComponent(imgSAGA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SAGALayout.setVerticalGroup(
            SAGALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SAGALayout.createSequentialGroup()
                .addComponent(imgSAGA, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaga)
                .addContainerGap())
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PERSONA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(S70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(X50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IRIZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(X70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SAGA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(476, 476, 476))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lblTitle)
                .addGap(42, 42, 42)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(X70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(X50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(S70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IRIZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PERSONA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SAGA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(exitButton))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//controller
    private void imgSAGAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgSAGAMouseClicked
        openCarDetails("Saga");
    }//GEN-LAST:event_imgSAGAMouseClicked

    private void imgIRIZMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgIRIZMouseClicked
        openCarDetails("Iriz");
    }//GEN-LAST:event_imgIRIZMouseClicked

    private void imgPERSONAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPERSONAMouseClicked
        openCarDetails("Persona");
    }//GEN-LAST:event_imgPERSONAMouseClicked

    private void imgX70MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgX70MouseClicked
        openCarDetails("X70");
    }//GEN-LAST:event_imgX70MouseClicked

    private void imgX50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgX50MouseClicked
        openCarDetails("X50");
    }//GEN-LAST:event_imgX50MouseClicked

    private void imgS70MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgS70MouseClicked
        openCarDetails("S70");
    }//GEN-LAST:event_imgS70MouseClicked

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0); // Close the application
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // Close the current frame
        this.dispose();

    new HomeFrame(userId, username).setVisible(true);
// Pass the userId if needed
    }//GEN-LAST:event_backButtonActionPerformed
    
    //controller
    private void openCarDetails(String model) {
        new CarDetailsFrame(model,userId, username).setVisible(true); // Open the CarDetailsFrame
        this.dispose(); // Close current frame
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllModelFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IRIZ;
    private javax.swing.JPanel PERSONA;
    private javax.swing.JPanel S70;
    private javax.swing.JPanel SAGA;
    private javax.swing.JPanel X50;
    private javax.swing.JPanel X70;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel background;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel imgIRIZ;
    private javax.swing.JLabel imgPERSONA;
    private javax.swing.JLabel imgS70;
    private javax.swing.JLabel imgSAGA;
    private javax.swing.JLabel imgX50;
    private javax.swing.JLabel imgX70;
    private javax.swing.JLabel lblIriz;
    private javax.swing.JLabel lblPersona;
    private javax.swing.JLabel lblS70;
    private javax.swing.JLabel lblSaga;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblX50;
    private javax.swing.JLabel lblX70;
    // End of variables declaration//GEN-END:variables
}
