/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ezzah
 */
public class HomeFrame extends javax.swing.JFrame {
    private String userId;
    private String username;
    
    /**
     * Creates new form HomeFrame
     */
    
    public HomeFrame(String userId, String username) {
        this.userId = userId;
        this.username = username;
        initComponents();
        this.setLocationRelativeTo(null);

        welcomeLabel.setText("Welcome, " + username + "!");
        
        // Fetch and set images for labels
        String imagePath1 = getCarImagePath("X50");  
        String imagePath2 = getCarImagePath("X70");  

        setImageToLabel(carImageLabel1, imagePath1);
        setImageToLabel(carImageLabel2, imagePath2);
    }

    HomeFrame() {
         initComponents();
    }

    // Method to load image into JLabel from database path
    private void setImageToLabel(JLabel label, String imagePath) {
        if (imagePath == null || imagePath.isEmpty()) {
            System.out.println("No image path found!");
            label.setText("No Image");
            return;
        }

        try {
            // Load image from resources
            java.net.URL imgURL = getClass().getClassLoader().getResource(imagePath);

            if (imgURL != null) {
                ImageIcon icon = new ImageIcon(imgURL);
                Image scaledImage = icon.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
                label.setIcon(new ImageIcon(scaledImage));
                System.out.println("Image loaded: " + imagePath);
            } else {
                System.out.println("ERROR: Image NOT FOUND -> " + imagePath);
                label.setText("Image Not Found");
            }
        } catch (Exception e) {
            e.printStackTrace();
            label.setText("Error Loading Image");
        }
    }
    
    // Fetch image path from the database based on selected car model
    private String getCarImagePath(String model) {
        String imagePath = "";
        String query = "SELECT image_path FROM car_details WHERE model = ? LIMIT 1";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setString(1, model);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                imagePath = rs.getString("image_path");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        }

        return imagePath;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background4 = new Styles.GradientPanel();
        menuBg4 = new javax.swing.JPanel();
        menuModel = new javax.swing.JLabel();
        menuCalc = new javax.swing.JLabel();
        menuComparison = new javax.swing.JLabel();
        logo4 = new javax.swing.JLabel();
        logoutButton = Styles.createRoundedButton("Logout");
        welcomeLabel = new javax.swing.JLabel();
        viewHistoryButton = Styles.createRoundedButton("VIEW HISTORY");
        loanCalculatorButton = Styles.createRoundedButton("LOAN CALCULATOR");
        jLabel9 = new javax.swing.JLabel();
        btnTestDrive = Styles.createRoundedButton("LOAN CALCULATOR");
        btnModel = Styles.createRoundedButton("LOAN CALCULATOR");
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        carImageLabel1 = new javax.swing.JLabel();
        carImageLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loan Calculation System");

        background4.setPreferredSize(new java.awt.Dimension(985, 599));

        menuBg4.setBackground(new java.awt.Color(0, 0, 0));

        menuModel.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        menuModel.setForeground(new java.awt.Color(255, 255, 255));
        menuModel.setText("Models");
        menuModel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuModelMouseClicked(evt);
            }
        });

        menuCalc.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        menuCalc.setForeground(new java.awt.Color(255, 255, 255));
        menuCalc.setText("Loan Calculator");
        menuCalc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCalcMouseClicked(evt);
            }
        });

        menuComparison.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        menuComparison.setForeground(new java.awt.Color(255, 255, 255));
        menuComparison.setText("Compare Models");
        menuComparison.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuComparisonMouseClicked(evt);
            }
        });

        // Load carImageLabel1 from "Images" folder inside the project
        java.net.URL imgURL = getClass().getResource("/Images/proton.png");

        // Check if the carImageLabel1 exists
        if (imgURL != null) {
            ImageIcon icon = new ImageIcon(imgURL);

            // Resize the carImageLabel1 to fit the label
            Image carImageLabel1 = icon.getImage().getScaledInstance(230, 60, Image.SCALE_SMOOTH);
            logo4.setIcon(new ImageIcon(carImageLabel1));
        } else {
            System.out.println("❌ ERROR: Image NOT FOUND -> Images/proton.png");
        }

        logoutButton.setBackground(new java.awt.Color(204, 51, 0));
        logoutButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBg4Layout = new javax.swing.GroupLayout(menuBg4);
        menuBg4.setLayout(menuBg4Layout);
        menuBg4Layout.setHorizontalGroup(
            menuBg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBg4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logo4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(menuModel)
                .addGap(61, 61, 61)
                .addComponent(menuCalc)
                .addGap(57, 57, 57)
                .addComponent(menuComparison)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        menuBg4Layout.setVerticalGroup(
            menuBg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBg4Layout.createSequentialGroup()
                .addGroup(menuBg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuBg4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBg4Layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addGroup(menuBg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menuModel)
                            .addComponent(menuCalc)
                            .addComponent(menuComparison)
                            .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)))
                .addContainerGap())
        );

        welcomeLabel.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        welcomeLabel.setText("Welcome, [username]!");

        viewHistoryButton.setBackground(new java.awt.Color(0, 0, 0));
        viewHistoryButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        viewHistoryButton.setForeground(new java.awt.Color(255, 255, 255));
        viewHistoryButton.setText("View Loan History");
        viewHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHistoryButtonActionPerformed(evt);
            }
        });

        loanCalculatorButton.setBackground(new java.awt.Color(0, 0, 0));
        loanCalculatorButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        loanCalculatorButton.setForeground(new java.awt.Color(255, 255, 255));
        loanCalculatorButton.setText("Loan Calculator");
        loanCalculatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanCalculatorButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("2025 Proton Holdings Berhad");

        btnTestDrive.setBackground(new java.awt.Color(0, 0, 0));
        btnTestDrive.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnTestDrive.setForeground(new java.awt.Color(255, 255, 255));
        btnTestDrive.setText("Book Test Drive");
        btnTestDrive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestDriveActionPerformed(evt);
            }
        });

        btnModel.setBackground(new java.awt.Color(0, 0, 0));
        btnModel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnModel.setForeground(new java.awt.Color(255, 255, 255));
        btnModel.setText("View All Model");
        btnModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("Explore a world of premium cars designed for comfort,  perfoormance, and style. ");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel11.setText("DRIVE INTO THE FUTURE OF LUXURY AND INNOVATION");

        javax.swing.GroupLayout background4Layout = new javax.swing.GroupLayout(background4);
        background4.setLayout(background4Layout);
        background4Layout.setHorizontalGroup(
            background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBg4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(background4Layout.createSequentialGroup()
                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background4Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel11))
                    .addGroup(background4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnTestDrive)
                        .addGap(18, 18, 18)
                        .addComponent(btnModel)
                        .addGap(18, 18, 18)
                        .addComponent(loanCalculatorButton)
                        .addGap(18, 18, 18)
                        .addComponent(viewHistoryButton))
                    .addGroup(background4Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(carImageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(carImageLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(background4Layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(welcomeLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(background4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(206, 206, 206))))
        );
        background4Layout.setVerticalGroup(
            background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background4Layout.createSequentialGroup()
                .addComponent(menuBg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(1, 1, 1)
                .addComponent(jLabel10)
                .addGap(33, 33, 33)
                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carImageLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carImageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTestDrive, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanCalculatorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel9)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background4, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background4, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loanCalculatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanCalculatorButtonActionPerformed
        // TODO add your handling code here:
        new LoanCalculatorFrame(userId,username).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_loanCalculatorButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose(); // Close the HomeFrame
        new LoginForm().setVisible(true); // Open the LoginForm
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void btnTestDriveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestDriveActionPerformed
        // TODO add your handling code here:
        new TestDrive(userId,username).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnTestDriveActionPerformed

    private void btnModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelActionPerformed
        // TODO add your handling code here:
        new AllModelFrame(userId,username).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnModelActionPerformed

    private void menuCalcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCalcMouseClicked
        // TODO add your handling code here:
        new LoanCalculatorFrame(userId,username).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_menuCalcMouseClicked

    private void menuModelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuModelMouseClicked
        // TODO add your handling code here:
        new AllModelFrame(userId, username).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_menuModelMouseClicked

    private void menuComparisonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuComparisonMouseClicked
        // TODO add your handling code here:
        new CarComparisonFrame(userId, username).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_menuComparisonMouseClicked

    private void viewHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHistoryButtonActionPerformed
        // TODO add your handling code here:
        new HistoryFrame(userId, username).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_viewHistoryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background4;
    private javax.swing.JButton btnModel;
    private javax.swing.JButton btnTestDrive;
    private javax.swing.JLabel carImageLabel1;
    private javax.swing.JLabel carImageLabel2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton loanCalculatorButton;
    private javax.swing.JLabel logo4;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel menuBg4;
    private javax.swing.JLabel menuCalc;
    private javax.swing.JLabel menuComparison;
    private javax.swing.JLabel menuModel;
    private javax.swing.JButton viewHistoryButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
